model:
  # name: SVM
  name: weston
  # name: LogisticRegression
  # name: widrow

parameters:
  learning_rate:  0.01
  epochs: 100
  normalize: True
dataset:
  # name: generate
  # name: cancer
  name: iris